# Generated by Django 5.2.3 on 2025-07-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0002_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
            ],
            options={
                'unique_together': {('faculty', 'program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
            ],
            options={
                'unique_together': {('professor', 'course', 'faculty', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
                ('course_assignments', models.ManyToManyField(to='academic.courseassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
