# Generated by Django 5.2.3 on 2025-07-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('organization', '0001_initial'),
        ('users', '0003_alter_professor_managers_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course_assignments',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframes', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.faculty')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.program')),
            ],
            options={
                'unique_together': {('professor', 'course', 'faculty', 'program')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='schedules',
            field=models.ManyToManyField(to='academic.schedule'),
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
    ]
