# Generated by Django 5.2.3 on 2025-07-21 04:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_class_course_assignments_alter_class_options_and_more'),
        ('organization', '0001_initial'),
        ('users', '0003_alter_professor_managers_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timeframes',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professor', 'course', '_class', 'faculty', 'program', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')},
        ),
    ]
