# Generated by Django 5.2.3 on 2025-07-21 06:26

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_class_schedules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timeframe_json',
            field=django_jsonform.models.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
