# Generated by Django 5.2.3 on 2025-07-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_schedule_timeframe_json'),
        ('organization', '0001_initial'),
        ('users', '0004_student__class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professor', 'course', '_class', 'faculty', 'program', 'timeframe_json')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday',
        ),
    ]
