# Generated by Django 5.2.3 on 2025-07-23 11:14

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_schedule_friday_alter_schedule_monday_and_more'),
        ('users', '0002_alter_professor_user_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_definition', django_jsonform.models.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professor'),
        ),
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.course'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
