# Generated by Django 5.2.3 on 2025-07-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_evalationtemplate_alter_schedule__class_and_more'),
        ('organization', '0002_alter_program_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='generation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('faculty', 'program', 'generation', 'name')},
        ),
    ]
