# Generated by Django 5.2.3 on 2025-07-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_schedule_unique_together_and_more'),
        ('organization', '0001_initial'),
        ('users', '0004_student__class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professor', 'course', '_class', 'faculty', 'program')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timeframe_json',
        ),
    ]
