# Generated by Django 5.2.3 on 2025-07-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_schedule_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
