# Generated by Django 5.2.3 on 2025-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_global', 'Global Access'), ('access_faculty_wide', 'Faculty Wide Access'), ('access_program_wide', 'Program Wide Access')], 'verbose_name': 'User'},
        ),
    ]
