# Generated by Django 5.2.3 on 2025-07-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_schedule_professor'),
        ('users', '0002_alter_professor_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('_class', 'user')},
        ),
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academic.class'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
    ]
