# Generated by Django 5.2.3 on 2025-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0002_delete_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='professor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('user', 'faculty', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'faculty', 'program')},
        ),
    ]
