# Generated by Django 5.2.3 on 2025-07-14 06:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_faculty_options'),
        ('users', '0003_alter_customuser_faculty_alter_customuser_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='program',
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculties',
            field=models.ManyToManyField(to='organization.faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='programs',
            field=models.ManyToManyField(to='organization.program'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=16, null=True, region=None, unique=True),
        ),
    ]
