# Generated by Django 5.2.3 on 2025-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_unique_together_alter_student__class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
