# Generated by Django 5.2.3 on 2025-07-21 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_class_schedules_and_more'),
        ('users', '0003_alter_professor_managers_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.class'),
        ),
    ]
