# Generated by Django 5.2.3 on 2025-07-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_course_year'),
        ('users', '0004_customuser_is_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.class'),
        ),
    ]
