# Generated by Django 5.2.3 on 2025-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_faculty_options'),
        ('users', '0004_remove_customuser_faculty_remove_customuser_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculties',
            field=models.ManyToManyField(blank=True, to='organization.faculty'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='programs',
            field=models.ManyToManyField(blank=True, to='organization.program'),
        ),
    ]
