# Generated by Django 5.2.3 on 2025-07-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_schedule_unique_together_schedule_friday_and_more'),
        ('users', '0004_student__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.class'),
        ),
    ]
