# Generated by Django 5.2.3 on 2025-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_faculties_alter_customuser_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Professor'), (2, 'Staff')], default=2),
        ),
    ]
