# Generated by Django 5.2.3 on 2025-07-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_global', 'Global Access'), ('access_faculty_wide', 'Faculty Wide Access'), ('access_program_wide', 'Program Wide Access'), ('view_student', 'Can view Student'), ('add_student', 'Can add Student'), ('change_student', 'Can change Student'), ('delete_student', 'Can delete Student'), ('view_professor', 'Can view Professor'), ('add_professor', 'Can add Professor'), ('change_professor', 'Can change Professor'), ('delete_professor', 'Can delete Professor'), ('view_staff', 'Can view Staff'), ('add_staff', 'Can add Staff'), ('change_staff', 'Can change Staff'), ('delete_staff', 'Can delete Staff')], 'verbose_name': 'User'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
