# Generated by Django 5.2.3 on 2025-07-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
    ]
