# Generated by Django 5.2.3 on 2025-07-21 04:51

import apps.core.json_encoder
import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='template_json',
            field=django_jsonform.models.fields.JSONField(default=dict, encoder=apps.core.json_encoder.CustomJSONEncoder),
        ),
    ]
