# Generated by Django 5.2.3 on 2025-06-28 08:58

import apps.core.json_encoder
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='program',
        ),
        migrations.AlterField(
            model_name='activity',
            name='faculty',
            field=models.ForeignKey(default='1', help_text='The faculty this record is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_by_faculty', to='organization.faculty', verbose_name='Faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='response_json',
            field=models.JSONField(default=dict, encoder=apps.core.json_encoder.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='template_json',
            field=models.JSONField(default=dict, encoder=apps.core.json_encoder.CustomJSONEncoder),
        ),
    ]
