# Generated by Django 5.2.3 on 2025-07-21 08:53

import apps.core.json_encoder
import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activitytemplate_template_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='template_json',
            field=django_jsonform.models.fields.JSONField(encoder=apps.core.json_encoder.CustomJSONEncoder),
        ),
    ]
