# Generated by Django 5.2.3 on 2025-07-05 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_program_alter_activity_faculty_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set_by_faculty', to='organization.faculty', verbose_name='Faculty'),
        ),
    ]
