# Generated by Django 5.2.3 on 2025-07-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_updated_at'),
        ('organization', '0002_alter_program_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.program'),
        ),
    ]
