# Generated by Django 5.2.3 on 2025-06-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_options_activity_updated_at_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='The faculty this record is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set_by_faculty', to='organization.faculty', verbose_name='Faculty Affiliation'),
        ),
        migrations.AddField(
            model_name='activity',
            name='program',
            field=models.ForeignKey(blank=True, help_text='The program this record is associated with (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set_by_program', to='organization.program', verbose_name='Program Affiliation'),
        ),
    ]
