# Generated by Django 5.2.3 on 2025-07-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_faculty'),
        ('organization', '0002_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.faculty'),
        ),
    ]
