# Generated by Django 5.2.3 on 2025-06-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('access_program_wide', 'program-wide access'), ('access_faculty_wide', 'faculty-wide access'), ('access_global', 'university-wide access')]},
        ),
    ]
